// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RetailInventoryAPI.Data;

#nullable disable

namespace RetailInventoryAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RetailInventoryAPI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Groceries"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sports & Fitness"
                        });
                });

            modelBuilder.Entity("RetailInventoryAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Laptop",
                            Price = 75000m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Wireless Mouse",
                            Price = 1299m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "Bluetooth Speaker",
                            Price = 3499m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Name = "Men's T-Shirt",
                            Price = 499m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Name = "Running Shoes",
                            Price = 2999m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Name = "Basmati Rice 5kg",
                            Price = 350m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Name = "Olive Oil 1L",
                            Price = 649m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Name = "Yoga Mat",
                            Price = 799m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            Name = "Dumbbells Set",
                            Price = 2499m
                        });
                });

            modelBuilder.Entity("RetailInventoryAPI.Models.Product", b =>
                {
                    b.HasOne("RetailInventoryAPI.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("RetailInventoryAPI.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
